version: '3.8'

services:
  postgres:
    container_name: ecm_postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: ECMDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecm_network

  pgadmin:
    container_name: ecm_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - ecm_network

networks:
  ecm_network:
    driver: bridge

volumes:
  postgres_data: 